spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://${DB_IP}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
        show-sql: true

logging:
  level:
    org.springframework.security: DEBUG